version: "2"
services:
  server:
    container_name: sharex
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 5500:5500